### ISSUE TITLE
Is the playwright test generator part of this package? - https://playwright.dev/docs/codegen#running-codegen

### ISSUE THREAD

**Issue by ananthay** [nxkit/nxkit#12]
Is the playwright test generator part of this package? - https://playwright.dev/docs/codegen#running-codegen

**Comment by sebastiandg7** [comment]
Hello @ananthay, sorry if I didn't get your question. Nx plugins can contain code generators for your Nx workspace, read more about them here: https://nx.dev/plugin-features/use-code-generators.

This plugins contains a `project` generator to create playwright projects in your Nx workspace, which is different from the [playwright codegen feature](https://playwright.dev/docs/codegen).

I hope this helps.
