### ISSUE TITLE
Playwright project.json outputPath and actual path of output don't match

### ISSUE THREAD

**Issue by JoepKockelkorn** [nxkit/nxkit#63]
### Current Behavior

Generating a new project doesn't set the proper outputPath in the project.json (which leads to the e2e output not being recovered from cache in CI). When generating an e2e app for 'my-app' and running the e2e target, the actual outputPath is `dist/apps/my-app-e2e/playwright-report` while the config in the project.json points to `dist/apps/my-app-e2e/test-results`.

### Expected Behaviour

The output path of the reporters in the `playwright.config.ts` should match the outputpath in the e2e and debug targets in the `project.json`.

### Github Repo

https://github.com/JoepKockelkorn/nxkit-playwright-outputpath-bug

### Steps to Reproduce

1. run `npx nx generate @nxkit/playwright:project my-app-e2e --frontendProject=my-app --no-interactive`
2. run `npx nx e2e my-app-e2e`
3. see `dist/apps/my-app-e2e/playwright-report` folder is populated
4. delete that folder
5. rerun `npx nx e2e my-app-e2e`
6. see that the output is not recovered from cache because of the wrong outputpath in `project.json`

### Nx Report

```shell
Node : 16.16.0
OS   : darwin x64
npm  : 8.11.0

nx                      : 15.8.6
@nrwl/js                : 15.8.6
@nrwl/linter            : 15.8.6
@nrwl/workspace         : 15.8.6
@nrwl/cli               : 15.8.6
@nrwl/cypress           : 15.8.6
@nrwl/devkit            : 15.8.6
@nrwl/eslint-plugin-nx  : 15.8.6
@nrwl/react             : 15.8.6
@nrwl/tao               : 15.8.6
@nrwl/vite              : 15.8.6
typescript              : 4.9.5
---------------------------------------
Community plugins:
@nxkit/playwright : 2.1.2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoepKockelkorn** [comment]
I'll try to create a PR for it now

UPDATE: see below

**Comment by sebastiandg7** [comment]
Thank you @JoepKockelkorn!
