### ISSUE TITLE
Multi brand / theme support on Style Dictionary config

### ISSUE THREAD

**Issue by jgrodriguezc** [nxkit/nxkit#70]
### Is your feature request related to a problem?

No

### Describe the solution or feature you'd like

I'd like to have the possibility to add multiple configurations depends on brand or theme that i am build.

### Describe alternatives you've considered

I found [this example](https://github.com/amzn/style-dictionary/tree/main/examples/advanced/multi-brand-multi-platform) from Style Dictionary oficial repository, you could have something similar using an array of configuration instead of only one configuration object in `style-dictionary.config.ts`.

Later you could use that array of configuration to build something similar to the example.

### Additional context

This is a feature that i need to build different folders depending on which brand and theme those tokens belong.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebastiandg7** [comment]
@allcontributors please add @jgrodriguezc for ideas
