### ISSUE TITLE
Create project doesn't work

### ISSUE THREAD

**Issue by adrianiskandar** [nxkit/nxkit#76]
### Current Behavior

While running:  `npx nx generate @nxkit/playwright:project some-project`

It fails with this error:

```
>  NX  Generating @nxkit/playwright:project


 >  NX   (0 , js_1.initGenerator) is not a function

   Pass --verbose to see the stacktrace.
```

### Expected Behaviour

It shoudl work and create the project

### Steps to Reproduce

1. Install the dependency: `npm i -D @nxkit/playwright `
2. Try to run the command to create the project: `npx nx generate @nxkit/playwright:project some-project`

### Nx Report

```shell
>  NX  Generating @nxkit/playwright:project


 >  NX   (0 , js_1.initGenerator) is not a function

   Pass --verbose to see the stacktrace.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebastiandg7** [comment]
Hello @adrianiskandar. Can you please post the result of the `nx report` command?

**Comment by sebastiandg7** [comment]
This seems to be a duplicated of #74

**Comment by sebastiandg7** [comment]
Closing. Duplicate.
