### ISSUE TITLE
Include @nx/devkit as a dependency

### ISSUE THREAD

**Issue by isaacplmann** [nxkit/nxkit#90]
### Current Behavior

Both plugins (playwright and style-dictionary) don't have an Nx version listed in the [Nx Plugin Registry](https://nx.dev/extending-nx/registry) because the plugins don't include `@nx/devkit` as a dependency.  Could you please release a version that fixes that?

Thanks,
Isaac (Nx Team)

### Expected Behaviour

Add `@nx/devkit` as a `dependency` in `package.json`

### Steps to Reproduce

1. Check for an Nx version for the package on the [Nx Plugin Registry](https://nx.dev/extending-nx/registry)

### Nx Report

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebastiandg7** [comment]
Thanks Isaac. Including it in the next release.

**Comment by sebastiandg7** [comment]
@allcontributors add @isaacplmann for bug
