### ISSUE TITLE
Can't create style-dictionary library with nx 17

### ISSUE THREAD

**Issue by maxime4000** [nxkit/nxkit#93]
### Current Behavior

Can't create a new style-dictionary library with nx 17

>  NX  Generating @nxkit/style-dictionary:library
 >  NX   Cannot find module '@nx/workspace/src/utilities/run-tasks-in-serial'
   Require stack:
   - C:\path\to\repo\node_modules\@nxkit\style-dictionary\src\generators\library\generator.js

### Expected Behaviour

Generator would work

### Steps to Reproduce

have a repo using at least nx 17.0.2 and try creating a library

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : win32-x64
   npm    : 10.1.0

   nx (global)        : 17.0.2
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/nest           : 17.0.2
   @nx/next           : 17.0.2
   @nx/node           : 17.0.2
   @nx/react          : 17.0.2
   @nx/storybook      : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container  : 5.1.0
   @nx-tools/nx-prisma     : 5.1.0
   @nxkit/style-dictionary : 3.0.2
   nx-stylelint            : 17.0.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebastiandg7** [comment]
@allcontributors add @maxime4000 for bug

**Comment by sebastiandg7** [comment]
@maxime4000, you should be using v4 of the plugin for Nx v17. Check the compatibility table in the repo's README.
